//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NYHApp.Resources.Help {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NYHApp.Resources.Help.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estás seguro que deseas cerrar la propuesta para .
        /// </summary>
        public static string AreYouSureCloseProposal {
            get {
                return ResourceManager.GetString("AreYouSureCloseProposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrada.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Cierre.
        /// </summary>
        public static string CloseDate {
            get {
                return ResourceManager.GetString("CloseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar Propuesta.
        /// </summary>
        public static string CloseProposal {
            get {
                return ResourceManager.GetString("CloseProposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacto.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ayudame.
        /// </summary>
        public static string CreateHelp {
            get {
                return ResourceManager.GetString("CreateHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dedicación.
        /// </summary>
        public static string Dedication {
            get {
                return ResourceManager.GetString("Dedication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtros.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alta.
        /// </summary>
        public static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Electricidad.
        /// </summary>
        public static string IsElectricity {
            get {
                return ResourceManager.GetString("IsElectricity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Albañileria.
        /// </summary>
        public static string IsMansonry {
            get {
                return ResourceManager.GetString("IsMansonry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pintura.
        /// </summary>
        public static string IsPainting {
            get {
                return ResourceManager.GetString("IsPainting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fontaneria.
        /// </summary>
        public static string IsPlumbing {
            get {
                return ResourceManager.GetString("IsPlumbing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Baja.
        /// </summary>
        public static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Media.
        /// </summary>
        public static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nada.
        /// </summary>
        public static string Nothing {
            get {
                return ResourceManager.GetString("Nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fotografias.
        /// </summary>
        public static string Photos {
            get {
                return ResourceManager.GetString("Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Está buscando ayuda.
        /// </summary>
        public static string SearchHelp {
            get {
                return ResourceManager.GetString("SearchHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Título.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quiere ayudar.
        /// </summary>
        public static string WantHelp {
            get {
                return ResourceManager.GetString("WantHelp", resourceCulture);
            }
        }
    }
}
